# THE HIGH-LOW GUESSING GAME

import random #This allows the computer to pick a random number.

def hi_low(): #hi_low is the name of the function we are defining.

    hidden_number = random.randint(0, 100) #The hidden number is a random number(integer) between the range of 0-100 that is generated by the computer.

    print("Yuppie! Welcome to the Hi-Low guessing game!")

    print("The hidden number is between 0 and 100. It could be a high(big) number or a low(small) number.")

    print("Hints are given at every wrong attempt to show if you are closer or far from the hidden number.")

    print("Note: You end the game when you enter a number outside the range 0-100.")

    while True: #The while loop is implemented to allow the user to keep entering their guesses until they win or end the game.

        user_input = int(input("Enter your guess (or a number outside the range to end game): ")) #This prompts the user to input a number(integer). 

        if 0 <= user_input <= 100: #This condition is fulfilled when the user enters a number between 0-100

            if user_input == hidden_number: #If the user inputs the hidden number.

                print(f"Congratulations! You guessed the hidden number {hidden_number}!")

                break #This ends the game and the while loop stops because the user has won the game.

            elif user_input < hidden_number: #If the user inputs the hidden number.

                print("Too low! Try a higher number.") #This is a hint to show that the hidden number is a big number.

            else:

                print("Too high! Try a lower number.") #This is a hint to show that the hidden number is a big number.

        else: #This condition is fulfilled when the user enters a number outside  0-100

            print("You just ended the game. The hidden number was:", hidden_number)

hi_low() #After defining a function, the function must be called out in order to get executed. 